/******************************************************************************/
/*                 Generated by IBExpert 25/06/2024 13:36:35                  */
/******************************************************************************/

/******************************************************************************/
/*        Following SET SQL DIALECT is just for the Database Comparer         */
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/


CREATE GENERATOR GEN_CLIENTES_ID;

CREATE TABLE CLIENTES (
    ID             INTEGER NOT NULL,
    NOME_FANTASIA  VARCHAR(50) NOT NULL,
    RAZAO_SOCIAL   VARCHAR(50) NOT NULL,
    CNPJ           VARCHAR(14) NOT NULL,
    ENDERECO       VARCHAR(100) NOT NULL,
    TELEFONE       INTEGER
);



/******************************************************************************/
/*                                Primary keys                                */
/******************************************************************************/

ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTES PRIMARY KEY (ID);


/******************************************************************************/
/*                                  Triggers                                  */
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/*                            Triggers for tables                             */
/******************************************************************************/

CREATE EXCEPTION EX_TELEFONE_IS_NOT_NULL 'O campo telefone é obrigatório, favor informe.';

COMMENT ON EXCEPTION EX_TELEFONE_IS_NOT_NULL IS 
'Exceção para validação de campo telefone é obrigatório';

GRANT USAGE ON EXCEPTION EX_TELEFONE_IS_NOT_NULL TO SYSDBA WITH GRANT OPTION;


/* Trigger: CLIENTES_BI */
CREATE OR ALTER TRIGGER CLIENTES_BI FOR CLIENTES
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_clientes_id,1);

  if (new.telefone is null) then
  begin
    EXCEPTION EX_TELEFONE_IS_NOT_NULL;
  end
    
end
^
SET TERM ; ^



/******************************************************************************/
/*                                 Privileges                                 */
/******************************************************************************/

/******************************************************************************/
/*                 Generated by IBExpert 25/06/2024 13:39:12                  */
/******************************************************************************/

/******************************************************************************/
/*        Following SET SQL DIALECT is just for the Database Comparer         */
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/


CREATE GENERATOR GEN_PRODUTOS_ID;

CREATE TABLE PRODUTOS (
    ID         INTEGER NOT NULL,
    DESCRICAO  VARCHAR(100) NOT NULL,
    MARCA      VARCHAR(30) NOT NULL,
    PRECO      NUMERIC(15,2) NOT NULL
);



/******************************************************************************/
/*                                Primary keys                                */
/******************************************************************************/

ALTER TABLE PRODUTOS ADD CONSTRAINT PK_PRODUTOS PRIMARY KEY (ID);


/******************************************************************************/
/*                                  Triggers                                  */
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/*                            Triggers for tables                             */
/******************************************************************************/



/* Trigger: PRODUTOS_BI */
CREATE OR ALTER TRIGGER PRODUTOS_BI FOR PRODUTOS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_produtos_id,1);
end
^
SET TERM ; ^



/******************************************************************************/
/*                                 Privileges                                 */
/******************************************************************************/


/******************************************************************************/
/*                 Generated by IBExpert 25/06/2024 13:38:52                  */
/******************************************************************************/

/******************************************************************************/
/*        Following SET SQL DIALECT is just for the Database Comparer         */
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/


CREATE GENERATOR GEN_PEDIDOS_ID;

CREATE TABLE PEDIDOS (
    ID           INTEGER NOT NULL,
    ID_CLIENTE   INTEGER,
    VALOR_TOTAL  NUMERIC(15,2) NOT NULL,
    DATA         TIMESTAMP NOT NULL
);



/******************************************************************************/
/*                                Primary keys                                */
/******************************************************************************/

ALTER TABLE PEDIDOS ADD CONSTRAINT PK_PEDIDOS PRIMARY KEY (ID);


/******************************************************************************/
/*                                Foreign keys                                */
/******************************************************************************/

ALTER TABLE PEDIDOS ADD CONSTRAINT FK_PEDIDOS_ID_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID);


/******************************************************************************/
/*                                  Triggers                                  */
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/*                            Triggers for tables                             */
/******************************************************************************/



/* Trigger: PEDIDOS_BI */
CREATE OR ALTER TRIGGER PEDIDOS_BI FOR PEDIDOS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_pedidos_id,1);
end
^
SET TERM ; ^



/******************************************************************************/
/*                                 Privileges                                 */
/******************************************************************************/

/******************************************************************************/
/*                 Generated by IBExpert 25/06/2024 13:40:17                  */
/******************************************************************************/

/******************************************************************************/
/*        Following SET SQL DIALECT is just for the Database Comparer         */
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/


CREATE GENERATOR GEN_PEDIDOS_ITENS_ID;

CREATE TABLE PEDIDOS_ITENS (
    ID              INTEGER NOT NULL,
    ID_PEDIDO       INTEGER,
    ID_PRODUTO      INTEGER,
    QUANTIDADE      NUMERIC(15,2) NOT NULL,
    VALOR_UNITARIO  NUMERIC(15,2) NOT NULL,
    VALOR_TOTAL     NUMERIC(15,2) NOT NULL
);



/******************************************************************************/
/*                                Primary keys                                */
/******************************************************************************/

ALTER TABLE PEDIDOS_ITENS ADD CONSTRAINT PK_PEDIDOS_ITENS PRIMARY KEY (ID);


/******************************************************************************/
/*                                Foreign keys                                */
/******************************************************************************/

ALTER TABLE PEDIDOS_ITENS ADD CONSTRAINT FK_PEDIDOS_ITENS_ID_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS (ID);
ALTER TABLE PEDIDOS_ITENS ADD CONSTRAINT FK_PEDIDOS_ITENS_ID_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS (ID);


/******************************************************************************/
/*                                  Triggers                                  */
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/*                            Triggers for tables                             */
/******************************************************************************/



/* Trigger: PEDIDOS_ITENS_BI */
CREATE OR ALTER TRIGGER PEDIDOS_ITENS_BI FOR PEDIDOS_ITENS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_pedidos_itens_id,1);
end
^
SET TERM ; ^



/******************************************************************************/
/*                                 Privileges                                 */
/******************************************************************************/

